# netlify.toml

# Эта секция говорит Netlify, как обрабатывать запросы
[[redirects]]
  # Все запросы, начинающиеся с /proxy/
  from = "/proxy/*"
  # должны быть направлены на нашу функцию proxy.js
  to = "/.netlify/functions/proxy"
  # Статус 200 означает, что это "перезапись" (rewrite), а не редирект. Это важно!
  status = 200